- room-app/build.gradle
- room-app/src/main/java/net/wasdev/gameon/room/LifecycleManager.java
- room-wlpcfg/servers/gameon-room/server.xml
Periodic Room ReRegistration, via a managed scheduled executor. 
Slightly complicated by the fact that a ServerApplicationConfig is not an eligible target for resource injection.. so had to use jndi lookup instead.
> Periodic room re-registration for concierge restarts

- room-app/src/main/java/net/wasdev/gameon/room/LifecycleManager.java
- room-app/src/main/java/net/wasdev/gameon/room/RoomWS.java
- room-app/src/main/java/net/wasdev/gameon/room/engine/sample/commands/Look.java
Tweak the verb casing, add leading / and fix some sysouts
> minor fixes

- room-app/src/main/java/net/wasdev/gameon/room/RoomWS.java
> AddInitialRoomAck

- room-app/src/main/java/net/wasdev/gameon/room/engine/Room.java
- room-app/src/main/java/net/wasdev/gameon/room/engine/sample/SampleDataProvider.java
- room-app/src/main/java/net/wasdev/gameon/room/engine/sample/items/Items.java
> Fix state on force-drop or reset. Add MugRoomSign

- room-app/src/main/java/net/wasdev/gameon/room/engine/sample/commands/Drop.java
> Actually clear state on drop

- room-app/src/main/java/net/wasdev/gameon/room/Constants.java
- room-app/src/main/java/net/wasdev/gameon/room/LifecycleManager.java
- room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java
- room-wlpcfg/build.gradle
- room-wlpcfg/servers/gameon-room/server.xml
- room-wlpcfg/startup.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/61)
> Make sys id an env var

- .gitignore
- room-app/src/main/java/net/wasdev/gameon/room/GameOnWSHandshakeAuth.java
- room-app/src/main/java/net/wasdev/gameon/room/LifecycleManager.java
- room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java
- room-app/src/main/java/net/wasdev/gameon/room/engine/Room.java
- room-wlpcfg/servers/gameon-room/server.xml
- room-wlpcfg/startup.sh
Signed-off-by: Adam Pilkington <apilkington@uk.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/63)
> Rooms validate that the Origin header matches their registration

- room-wlpcfg/servers/gameon-room/server.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/64)
> Remove recroom token.

- room-wlpcfg/servers/gameon-room/kafkaDropin.xml
> Add root server element.

- room-app/src/main/java/net/wasdev/gameon/room/Kafka.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/67)
> Cacerts location update.

- room-app/src/main/java/net/wasdev/gameon/room/Kafka.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/68)
> Add missing imports

- room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/71)
> Alter the order of the builder to avoid unwanted log output

- room-app/src/main/java/net/wasdev/gameon/room/Kafka.java
Update kafka to be more cdi beanlike.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/72)
> Kafka beanification.

- room-wlpcfg/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/73)
> cacheable dockerfile, update maintainer

- build.gradle
- room-wlpcfg/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/74)
> cache-friendly dockerfile, package/maintainer

- idsBuild.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/78)
> NoDockerFileLiveForRoom

- room-wlpcfg/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/79)
> Stop using gradle plugin

- room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/81)
> SSL changes

- room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java
Use 'build' not 'newClient' and move the client ssl config
logic to a common method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/82)
> Set SSL Configuration for Outbound Client

- room-wlpcfg/startup.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/85)
> Eliminate extra steps, use CONTAINER_NAME

- room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java
Fixes #83 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/86)
> Don't shutdown managed executor

- room-wlpcfg/servers/gameon-room/bluemix-logCollector.xml
- room-wlpcfg/servers/gameon-room/bluemix-messageHub.xml
- room-wlpcfg/servers/gameon-room/local-config.xml
- room-wlpcfg/servers/gameon-room/server.xml
- room-wlpcfg/startup.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/87)
> use TARGET_PLATFORM for config

- room-wlpcfg/servers/gameon-room/bluemix-logCollector.xml
Update config to match latest beta.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/88)
> Update log collector xml

- room-app/src/main/java/net/wasdev/gameon/room/Constants.java
- room-app/src/main/java/net/wasdev/gameon/room/LifecycleManager.java
- room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java
- room-wlpcfg/Dockerfile
- room-wlpcfg/servers/gameon-room/server.xml
- room-wlpcfg/startup.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/90)
> Remove a8, consolidate ENV vars

- room-app/src/main/java/net/wasdev/gameon/room/Constants.java
- room-app/src/main/java/net/wasdev/gameon/room/RoomRegistrationHandler.java
- room-wlpcfg/servers/gameon-room/jvm.options
- room-wlpcfg/servers/gameon-room/server.xml
- room-wlpcfg/startup.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/91)
> correct env var; check map health

- room-app/src/main/java/net/wasdev/gameon/room/Health.java
- room-app/src/main/webapp/index.html
- room-app/src/main/webapp/websocketClient.js
- room-wlpcfg/startup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/94)
> websocket test page for sanity

- .gitignore
- README.md
- room-app/build.gradle
- room-app/src/main/java/net/wasdev/gameon/room/RoomWS.java
- room-wlpcfg/Dockerfile
- room-wlpcfg/build.gradle
- room-wlpcfg/servers/gameon-room/server.xml
Added Metrics, Fault Tolerance, Fallback, and Tracing MicroProfile Features.
Zipkin user feature needed to be downloaded and unzipped locally using gradle. The feature is then copied over to the docker container so the server.xml can pick up the feature at runtime to configure the zipkin host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/95)
> MP Metrics, FaultTolerance, FallBack, and Open Tracing Configured

- .gitignore
- README.md
- room-app/build.gradle
- room-app/src/main/java/net/wasdev/gameon/room/LogView.java
- room-app/src/main/java/net/wasdev/gameon/room/RoomWS.java
- room-app/src/main/webapp/index.html
- room-app/src/main/webapp/websocketClient.js
- room-wlpcfg/Dockerfile
- room-wlpcfg/build.gradle
- room-wlpcfg/servers/gameon-room/server.xml
- room-wlpcfg/startup.sh
This is an update to #95 removing opentracing. 
(Also fixes a LogView issue)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/96)
> Microprofile (updated)

- room-wlpcfg/Dockerfile
- room-wlpcfg/startup.sh
move up to level of base image using UBI
alter jvm system truststore location to match the one in the new base image.
Minikube/Docker need testing before this goes non-draft.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gameontext/gameon-room/97)
> Move to UBI Base Image
